<?php

// namespaces
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_helps().
 */
function learn_module_help($route_name, RouteMatchInterface $route_match) 
{
	switch ($route_name) 
	{
 		case 'help.page.learn_module':
 			$output = '';
 			$output .= '<h3>' . t('About') .'</h3>';
 			$output .= '<p>' . t('This is an example module created by spaker.') . '</p>';
 			return $output;
 		default;
	}
}