<?php

/**
 * @file 
 * learn module file.(for respecting dru coding conventions)
 */

// namespaces
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_helps().
 * is not a custom hook, that is just for extend help() hook
 * to make particular for our module
 */
function learn_module_help($route_name, RouteMatchInterface $route_match) 
{
	switch ($route_name) 
	{
 		case 'help.page.learn_module':
 			$output = '';
 			$output .= '<h3>' . t('About learn module') .'</h3>';
 			$output .= '<p>' . t('This is an example module created by spaker [learning purpose].') . '</p>';
 			return $output;
 		default;
	}
}